name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      # Run lint, test, build, and e2e-ci tasks for affected projects
      - run: npx nx affected -t lint test build e2e-ci

      # Build your Angular application
      - name: Build Angular App
        run: npx nx build angular-monorepo --configuration production --base-href /angular-monorepo/

      # Upload artifact for deployment
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist/apps/angular-monorepo

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write # To deploy to GitHub Pages
      id-token: write # To authenticate to GitHub's OIDC provider
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
