name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.upload_pages.outputs.artifact_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      # Run lint, test, build, and e2e-ci tasks for affected projects
      - run: npx nx affected -t lint test build e2e-ci

      # Build your Angular application
      - name: Build Angular App
        run: npx nx build angular-monorepo --configuration production --base-href /angular-monorepo/

      # Upload artifact for deployment
      - name: Upload artifact
        id: upload_pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist/apps/angular-monorepo

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write # To deploy to GitHub Pages
      id-token: write # To authenticate to GitHub's OIDC provider
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
